language: python

branches:
  expect:
    - master

cache:
- pip

python:
- '2.7'

install:
- pip install nikola

before_script:
- echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- git config --global user.name "Swind (via Travis-CI)"
- git config --global user.email "swind@code-life.info"
- git clone --quiet https://${GH_TOKEN}@github.com/Swind/swind.github.com -b master output > /dev/null

script:
- nikola build

after_success:
- cd output
- git add .
- git commit -m "Update output from Travis CI"
- git push origin master

env:
  global:
    secure: bgD+Q7LIpym+pEmrL2+Ro3VfCLhSOGddRDcDXQoA6wAoL7ZIlXeVSgh2Q/iLy1SlEwIVhA+M9wPCDXbhRgWT54/qgDofwutLTmGZCU2ACN3XH4ZVfrqP13FdQ/+qiSRyOBnlmqPlxnDt6gHI7aRpC0fsBLIFiwWYpLDuqhWK2LU=
