dist: trusty
branches:
  except:
  - master
addons:
  apt:
    packages:
    - python-pygments
before_script:
- echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- git config --global user.name "Swind (via Travis-CI)"
- git config --global user.email "swind@code-life.info"
- rm -rf public
- git clone --quiet https://${GH_TOKEN}@github.com/Swind/swind.github.com -b master
  public > /dev/null
script:
- "./bin/hugo"
after_success:
- cd public
- git add .
- git status
- git commit -m "[ci skip] Update output from Travis CI"
- git push origin master
env:
  global:
    secure: dQ+EVg2w6Q83L+Fpt+7txxLsI2CRADJzZlpJ3V7/QNCDuRV0QKMmt/kwrleZtfmqNaVlaoE58ZIW4IdxiNbvs2ttxCeI/DEbTiLIjwZf0ZOnH+dJrsslbanHWRoxRhyFirUAHbWyFsqdC7zmO7LH0lXErEt1HyK03icZIQWEbLw=
