language: python

branches:
  only:
    - source

cache:
  - pip

python:
  - "2.7"

# command to install dependencies
install: 
  - "pip install nikola"

# command to run tests
before_script: 
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - git config --global user.name "Swind (via Travis-CI)"
  - git config --global user.email "swind@code-life.info"
  - git clone git@github.com:Swind/swind.github.com.git -b master output

script: 
  - "nikola build"

after_success:
  - cd output
  - git add .
  - git commit -m "Update output from Travis CI"
  - git push origin source

