# blacklist
branches:
  except:
    - master

addons:
  apt:
    packages:
      - python-pygments

before_script:
- echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- git config --global user.name "Swind (via Travis-CI)"
- git config --global user.email "swind@code-life.info"
- git clone --quiet https://${GH_TOKEN}@github.com/Swind/swind.github.com -b master public > /dev/null

script:
- ./bin/hugo 

after_success:
- cd public 
- git add .
- git commit -m "[ci skip] Update output from Travis CI"
- git push origin master

env:
  global:
    secure: bgD+Q7LIpym+pEmrL2+Ro3VfCLhSOGddRDcDXQoA6wAoL7ZIlXeVSgh2Q/iLy1SlEwIVhA+M9wPCDXbhRgWT54/qgDofwutLTmGZCU2ACN3XH4ZVfrqP13FdQ/+qiSRyOBnlmqPlxnDt6gHI7aRpC0fsBLIFiwWYpLDuqhWK2LU=
