baseurl = "https://swind.github.io/"
languageCode = "zh-tw"
title = "Corleonis"
author = "Swind"

canonifyurls = true
paginate = 10 # Number of posts to show before paginating


enableRobotsTXT = true # Suggested, enable robots.txt file
googleAnalytics = "UA-42855873-1" # Optional, add tracking Id for analytics
disqusShortname = "corleonis" # Optional, add Disqus shortname for comments
SectionPagesMenu = "main" # Enable menu system for lazy bloggers
footnoteReturnLinkContents = "↩" # Provides a nicer footnote return link

theme = "beautifulhugo" # Uncomment to use as default theme

[Params]
  hide_author = false # Optional, set true to hide author name on posts
  show_menu = true # Optional, set true to enable section menu
  powered_by = false # Optional, set false to disable credits
  images = [] # Suggested, controls default Open Graph images
  theme_variant = "" # Optional, for use to overriding default theme
  highlightjs = "monokai"
  commit = false
  rss = true
  comments = true

[[menu.main]]
  name = "Home"
  weight = 1
  identifier = "home"
  url = "/"

[[menu.main]]
  name = "Posts"
  weight = 2 
  identifier = "post"
  url = "/post/"
